name: club_management_project
description: "A Flutter project for managing clubs."

publish_to: 'none' # Private project, not published to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1      # Kullanıcı kayıt ve login için
  cloud_firestore: ^6.0.3     # Kulüp bilgileri ve veritabanı işlemleri
  provider: ^6.0.6            # State management
  google_generative_ai: ^0.4.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Eğer ileride resim, font gibi asset ekleyeceksen buraya ekle
  # assets:
  #   - assets/images/
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
