name: club_management_project
description: "A Flutter project for managing clubs."

publish_to: 'none' # Private project, not published to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1      # Kullanıcı kayıt ve login için
  cloud_firestore: ^6.0.3     # Kulüp bilgileri ve veritabanı işlemleri
  provider: ^6.0.6            # State management
  google_generative_ai: ^0.4.4
  image_picker: ^1.2.1
  firebase_storage: ^13.0.4
  http: ^1.6.0
  table_calendar: ^3.2.0
  intl: ^0.20.2
  google_fonts: ^6.3.2
  carousel_slider: ^5.1.1
  url_launcher: ^6.3.2
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1




flutter:
  uses-material-design: true

 

  assets:
    - assets/       
    # - assets/images/  <-- Eğer images klasörü içindeyse bunu açmalısın. 

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.jpeg" # <-- SONUNDAKİ UZANTIYI DEĞİŞTİRDİK
  min_sdk_android: 21
